name: First Workflow
on: [push]
run-name: ${{ github.actor }} first workflow
jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string 
              run: echo "This is my first workflow"
            - name: Multiline Command
              run: |
                node -v 
                npm -v

        


