name: First Workflow
on: [push]
run-name: ${{ github.actor }} first workflow
jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string 
              run: echo "This is my first workflow"
            - name: Multiline Command
              run: |
                node -v 
                npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers

    dependant-job:
        runs-on: windows-latest
        needs: [run-shell-commands]
        steps:
            - name: echo string  on windows
              run: Write-Output "Windows String"
            - name: Error steps
              run: |
                try {
                    doesnotexits
                } catch {
                    Write-Output "An error occurred: $_"
                }


