name: Git checkout
on: [push]
run-name: ${{github.actor}}

jobs:
    git-checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -la 
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main 
            - name: List Files After
              run: ls -la 