name: Git checkout
on: [push]
run-name: ${{github.actor}}
jobs:
    git-checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -la 
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main 
            - name: List Files After
              run: ls -la 

    git-checkout-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -la 
            - name: Checkouts
              uses: actions/checkout@v6
            - name: List Files After
              run: ls -la 
            - uses: actions/checkout@v6
              with:
                # Default: ${{ github.repository }}
                repository: ''
                ref: ''
                # Default: ${{ github.token }}
                token: ''
                ssh-known-hosts: ''
                ssh-strict: ''
                ssh-user: ''
                persist-credentials: ''
                path: ''
                clean: ''
                filter: ''
                sparse-checkout: ''
                sparse-checkout-cone-mode: ''
                fetch-depth: ''
                fetch-tags: ''
                show-progress: ''
                lfs: ''
                submodules: ''
                set-safe-directory: ''
                github-server-url: ''