name: Introduction actions
run-name: ${{ github.actor }}
on: [push]

jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              id: great
              uses: actions/hello-world-javascript-action@main
              with:
                who-to-greet: Pierre
            - name: Log Greeting Time
              run: echo "${{ steps.great.outputs.time}}"
    
    Build-NodeJs-Action:
        runs-on: ubuntu-latest
        steps:
            - name: Build package
              uses: actions/checkout@v2
            - name: Set up NodeJs
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            - name: Update npm to latest version
              run: npm install -g npm@latest
            - name: Install NPM dependencies
              run: npm install
              working-directory: app
            - name: Run tests
              run: npm test
              working-directory: app