name: Pull request comment
run-name: ${{github.actor}}
on: 
    pull_request_target:
        types: [opened]
jobs:
    pull_request_comment:
        runs-on: ubuntu-latest
        steps: 
            - name: Comment on new pull requests
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: 'Thanks for contributing!' ,
                    });