name: working-dir-and-shell
run-name: ${{github.actor}} 
on: [push]
defaults:
    run: 
        shell: bash
jobs:
    display-wd-linux-info:
        runs-on: ubuntu-latest
        steps:
                - name: Display working Directory & List Files 
                  run: |
                    pwd
                    ls -la
                    echo $GITHUB_SHA
                    echo $GITHUB_REPOSITORY
                    echo $GITHUB_WORKSPACE
                - name: Change Working Directory
                  working-directory: /home/runner
                  run: pwd

    display-wd-windows-info:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
                - name: Display working Directory & List Files 
                  run: |
                    Get-Location
                    dir
                    echo $env:GITHUB_SHA
                    echo $env:GITHUB_REPOSITORY
                    echo $env:GITHUB_WORKSPACE
                - name: Python Shell
                  shell: python
                  run: |
                    import platform
                    print(platform.processor())
      
